name: Release
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build Docker container
        run: |
          docker build . --file Dockerfile --tag builder
      - name: Build artifacts
        run: |
          docker run --rm -v ${PWD}:/project builder make -j$(nproc) release
      - name: Upload Artifact
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          makeLatest: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          artifacts: "ScreenshotManager*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
